export function ResearchToolDisclaimer() {
  return (
    <div role="note" style={{ background: '#3a2f00', color: '#ffe58a', padding: '0.75rem 1rem', fontSize: '0.9rem' }}>
      <strong>Research tool only.</strong> This app runs historical simulations — it never places real
      trades and does not connect to any brokerage account. Backtest results are not investment advice
      and past performance is not indicative of future results. Sentiment scores are generated by an
      LLM and are heuristic, not a precision signal.
    </div>
  );
}
